languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
  - 'appinfo/application.php'
  - 'l10n/*'
  - 'vendor/*'
  - 'js/vendor/*'
  - 'templates/*'
  - 'css/*'
  - 'img/*'
  - 'tests/*'
  - 'build/*'
  - 'documentation/*'
  - 'controller/configapicontroller.php'
  - 'controller/filesapicontroller.php'
  - 'controller/previewapicontroller.php'
