sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  global:
    - CORE_BRANCH=stable8
    - APP_NAME=galleryplus
    - GH_REF: github.com/interfasys/galleryplus.git
    - secure: "cLmMqrbVZrvn2GAoVs6JWa5h70tzrAISjPZUfENjl0KYT6B84z3B94W/dGU+I2mxwvyBqEP+x83Bih2CxEflqc7tJmdqC+MM/ZZiigPX7RCjq5XHbzUpPpMbC8MFxT2K3jcFXUitfwZvNaZXJIiK3ZQJU4ayKaegLvI91x1SqH0="
    # Codacy credentials
    - secure: "JS+oBSHTeqiEf0bWn2LL15Dhb8O6Ne34hke6dDuCu5lJgMyDpEwezvCW5wuMy8xfyjDobWytxxDI+pB86UfyVMMuHI/RWYqtzmevjdUamS9JAU1kgsFcfL0XXMzgPsqykeIQdyxj0zkqLawJHetNtnENA3zYc9WyzmmM0b/0MSPr+AHtlejuFjSdpG0X3/PBCiU9mZqZScq8dwjE4PvFEdd1med2VLpsbl8d+V8M9nRTX/8d2sNzWk9k0jgerWyRT3FgGoGuVFFuePZR4XA8mcEnsXmsQ/AbvV+fZFKFcj2HZCJZqCkqhyY6x3JGqVMNk8uYmP9B4vINL+0ociAxfGM4099yv220Z76pGNE+/vGpSfHygx8BYd0KwSd0oJr5dxdik9OcN6DtsUjLVLr90LO1Z+R4FVQxuCo5oNfRL0kd8Ab84Dtir+jyOQWxWOKr38j/QPyo9Sb6HcICPMp/GpT+aPjxV737SM4OCr+FbJbkHfuQxy7qt0NOTe52apWAzTJHitHPKHN/A0PqMuoKU+IVx3QTkAg/ziQPY76XgNagrtvPSkv3iAPpbnrxLYTiX5skW6Na60YKBfYtCZwG8++FXQ767QXzB+SOTTRaob+VQ9XiBqU3vxu27/1hmXbnkWGgFCy9O6pk23BwRM4eILIzFNQz8Bt1iD118Vh+0MA="
    # Code Climate credentials
    - secure: "JC+cjv2o0cfFPlqd64sJKB9zZXaPrKtmoJdc+GZU3e4F1R/BCe0suMI9KOWhHHAkNH39tpA0oD6dcyJ0No8Eec3U5+if6nuXyIS0VhnCt2F86sjAE1CPD3qk8NCmvcQJVMVn8Lq8+HzcoK8hTB6QHyu8my6KQWvTCMRL6a3A/sOEBhwV3j/3owcMLvX6/TZkO0Y47nqkqwK+541BneWQ4sIud+PC82fronHRi783ohCj9LSm/Pzn+j7AkIF7olHjhOVV6J5ClsoQEYfgyxyjXSw7l6zhgAcT+r/4wY+ckc2x3Kleds0HvU5Fl3UXGOG3MpZWvhPTOc7o3E4M4qYwP9szKCXK+R6+BEhEp6jKem+3OoMDI75tUap5VKJQp8XKdnQyju2mDEj8gACllltw1TZJ0LxX4Rt+5hTVJcj3izmXu35bvVXIgCZC3Iwul3E0YnGvu4CtdT/uGHRWOifipCQyVMZAe74Syw0Iq/v79wymbZTOchmmzGeWzx79yeFkSbEN98p2nN0p7cS5/OULMgx1QyPqN9C7doeqUrVGgVU4wWlvnI0o2PSRz8485FtqXLIv7JET5oKeNYzWtW3aavLOn24ZOkJGOLsscIEzn70P1fTEPGNTq3PCcOCFmS+LEk5e3wxU/RdwihZMET4m1fxfsryW3eprz6ddJ6bpUf8="
  matrix:
    - DB=sqlite

branches:
  only:
    - stable8

cache:
  directories:
    # ${TRAVIS_BUILD_DIR} is /home/travis/build/interfasys/galleryplus/
    - ${TRAVIS_BUILD_DIR}/travis/php-cache
    - $HOME/.composer/cache

before_cache:
  # Archive the vendor folder. Watch closely!
  - cp -r ${TRAVIS_BUILD_DIR}/../core/apps/$APP_NAME/vendor ${TRAVIS_BUILD_DIR}/travis/php-cache/`php-config --vernum`

before_install:
  # Installing ownCloud
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP_NAME

  # Sets up the cache
  - sh -c "if [ ! -d ${TRAVIS_BUILD_DIR}/travis/php-cache/`php-config --vernum` ]; then mkdir -p ${TRAVIS_BUILD_DIR}/travis/php-cache/`php-config --vernum`; fi;"
  - rm -rf ${TRAVIS_BUILD_DIR}/../core/apps/$APP_NAME/vendor
  - sh -c "if [ -d ${TRAVIS_BUILD_DIR}/travis/php-cache/`php-config --vernum`/vendor ]; then cp -r ${TRAVIS_BUILD_DIR}/travis/php-cache/`php-config --vernum`/vendor ${TRAVIS_BUILD_DIR}/../core/apps/$APP_NAME; fi;"

  # Composer
  - cd ${TRAVIS_BUILD_DIR}/../core/apps/$APP_NAME
  - composer self-update
  - composer install -o --prefer-dist --no-interaction

script:
  # Test lint
  - php vendor/bin/parallel-lint --exclude travis --exclude vendor . vendor/composer vendor/symfony/yaml vendor/autoload.php
  # Generate API documentation
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.6' ]; then php vendor/bin/phpdoc run; fi"
  # Generate Wiki documentation
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.6' ]; then git submodule update --init; fi"
  # Send documentation to Github Pages
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.6' ]; then cd build/documentation; bash ./docpublisher.sh; fi"

matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=pgsql
  allow_failures:
    - php: hhvm
    - php: 7
  fast_finish: true
